/***********************************************************************/
/*                                                                     */
/*  FILE        :I2C.c                                                 */
/*  DATE        :Tue, Sep 05, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.52).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  

#include "iodefine.h"
#include "CMT.h"
#include "vect.h"
#include "typedefine.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif
#include "rxserial.h"

void main(void)
{
	
	
	init_serial();			// データ閲覧設定
	i2c_portset();			// マイコンポート設定
	i2c_set();			// I2C 通信設定

	
	gyro_set();			// ジャイロ設定データ送信
	
	// キャリブレーション
	cya();
	
	// 送信機信号処理設定
	receiver_main();
	
	
	time_CMT0();			// タイマー設定,タイマー開始
					// 割込みによるジャイロセンサのデータ取得
	
			
	while(1)receiver_main_while();	// 送信機信号処理
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
